t

diff --git a/.github/workflows/deploy-demo.yaml b/.github/workflows/deploy-demo.yaml
--- a/.github/workflows/deploy-demo.yaml
+++ b/.github/workflows/deploy-demo.yaml
@@ -17,32 +17,50 @@ env:
   ALB_LISTENER_RULE_ARN: "arn:aws:elasticloadbalancing:us-east-1:020856120665:listener-rule/app/dev-devops-course/a66599c576daed43/37db800791a435df/c5b7ff453c0dcc72"
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repo
-        uses: actions/checkout@v3
+  # build:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout repo
+  #       uses: actions/checkout@v3
 
-      - name: Login to Docker registry
-        uses: aws-actions/amazon-ecr-login@v1
+  #     - name: Login to Docker registry
+  #       uses: aws-actions/amazon-ecr-login@v1
 
-      - name: Build and push
-        uses: docker/build-push-action@v4
-        with:
-          context: .
-          push: true
-          tags: 020856120665.dkr.ecr.us-east-1.amazonaws.com/dev-devops-course-ecr:${{ github.run_number }}.${{ github.run_attempt }}
+  #     - name: Build and push
+  #       uses: docker/build-push-action@v4
+  #       with:
+  #         context: .
+  #         push: true
+  #         tags: 020856120665.dkr.ecr.us-east-1.amazonaws.com/dev-devops-course-ecr:${{ github.run_number }}.${{ github.run_attempt }}
 
   deploy:
-    needs: build
+    # needs: build
     runs-on: ubuntu-latest
     steps:
       - name: Get
         id: get
         run: |
+          # Get target group arn with weight=0 (i.e. inactive one)
+          INACTIVE_TARGET_GROUP=$(aws elbv2 describe-rules --rule-arns ${{ env.ALB_LISTENER_RULE_ARN }} --query="Rules[*].Actions[*].ForwardConfig.TargetGroups[?Weight==\`0\`].TargetGroupArn" --output text)
+
+          if [[ ${INACTIVE_TARGET_GROUP} == *"dev-devops-course-app-blue"* ]];
+          then
+            INACTIVE_SERVICE="dev-devops-course-app-blue"
+          elif [[ ${INACTIVE_TARGET_GROUP} == *"dev-devops-course-app-green"* ]];
+          then
+            INACTIVE_TARGET_GROUP="dev-devops-course-app-green"
+          else
+            echo "Failed to find inactive service."
+            exit 1
+          fi
+
+          echo $INACTIVE_SERVICE
+          echo "inactive_service=${INACTIVE_SERVICE}" >> GITHUB_OUTPUT
+          echo "inactive_target_group=${INACTIVE_TARGET_GROUP}" >> GITHUB_OUTPUT
+
           echo "test=green" >> $GITHUB_OUTPUT
       - name: Test
-        run: echo ${{ steps.get.outputs.test }}
+        run: echo ${{ steps.get.outputs.inactive_target_group }}
     # steps:
     #   - name: Get task definition
     #     run: aws ecs describe-task-definition --task-definition arn:aws:ecs:us-east-1:020856120665:task-definition/dev-devops-course --query="taskDefinition" > task-definition.json
