t

diff --git a/.github/workflows/deploy-demo.yaml b/.github/workflows/deploy-demo.yaml
--- a/.github/workflows/deploy-demo.yaml
+++ b/.github/workflows/deploy-demo.yaml
@@ -14,6 +14,7 @@ env:
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   AWS_REGION: "us-east-1"
+  ALB_LISTENER_RULE_ARN: "arn:aws:elasticloadbalancing:us-east-1:020856120665:listener-rule/app/dev-devops-course/a66599c576daed43/37db800791a435df/c5b7ff453c0dcc72"
 
 jobs:
   build:
@@ -47,10 +48,53 @@ jobs:
           container-name: app
           image: 020856120665.dkr.ecr.us-east-1.amazonaws.com/dev-devops-course-ecr:${{ github.run_number }}.${{ github.run_attempt }}
 
+      - name: Get inactive ECS service
+        id: get_ecs_service
+        run: |
+          # Get target group arn with weight=0 (i.e. inactive one)
+          INACTIVE_TARGET_GROUP=$(aws elbv2 describe-rules --rule-arns ${{ env.ALB_LISTENER_RULE_ARN }} --query="Rules[*].Actions[*].ForwardConfig.TargetGroups[?Weight==\`0\`].TargetGroupArn" --output text)
+
+          if [[ ${INACTIVE_TARGET_GROUP} == *"dev-devops-course-app-blue"* ]];
+          then
+            INACTIVE_SERVICE="dev-devops-course-app-blue"
+          elif [[ ${INACTIVE_TARGET_GROUP} == *"dev-devops-course-app-green"* ]];
+          then
+            INACTIVE_TARGET_GROUP="dev-devops-course-app-green"
+          else
+            echo "Failed to find inactive service."
+            exit 1
+          fi
+          echo inactive_service=$INACTIVE_SERVICE >> GITHUB_OUTPUT
+          echo inactive_target_group=$INACTIVE_TARGET_GROUP >> GITHUB_OUTPUT
+
       - name: Deploy Amazon ECS task definition
         uses: aws-actions/amazon-ecs-deploy-task-definition@v1
         with:
           task-definition: ${{ steps.task-def.outputs.task-definition }}
-          service: dev-devops-course
+          service: ${{ steps.get_ecs_service.outputs.inactive_service }}
           cluster: dev-devops-course
           wait-for-service-stability: true
+
+      - name: Switch traffic
+        run: |
+          active_target_group=$(aws elbv2 describe-rules --rule-arns ${{ env.ALB_LISTENER_RULE_ARN }} --query="Rules[*].Actions[*].ForwardConfig.TargetGroups[?Weight==\`100\`].TargetGroupArn" --output text)
+
+          # Quick check to see if target groups have not mixed up
+          if [[ ${active_target_group} == ${{ steps.get_ecs_service.outputs.inactive_target_group }} ]];
+          then
+            echo "Active target group is the same as the inactive one."
+            exit 1
+          fi
+
+
+          aws elbv2 modify-rule --rule-arn ${{ env.ALB_LISTENER_RULE_ARN }} --actions \
+            '[{
+                "Type": "forward",
+                "Order": 1,
+                "ForwardConfig": {
+                  "TargetGroups": [
+                      {"TargetGroupArn": "${{ steps.get_ecs_service.outputs.inactive_target_group }}", "Weight": 100 },
+                      {"TargetGroupArn": "${active_target_group}", "Weight": 0 }
+                  ]
+                }
+            }]'
