t

diff --git a/.github/workflows/deploy-demo.yaml b/.github/workflows/deploy-demo.yaml
--- a/.github/workflows/deploy-demo.yaml
+++ b/.github/workflows/deploy-demo.yaml
@@ -42,6 +42,17 @@ jobs:
         run: |
           INACTIVE_TARGET_GROUP=$(aws elbv2 describe-rules --rule-arns ${{ env.ALB_LISTENER_RULE_ARN }} --query="Rules[*].Actions[*].ForwardConfig.TargetGroups[?Weight==\`0\`].TargetGroupArn" --output text)
 
+          if [[ ${INACTIVE_TARGET_GROUP} == *"dev-devops-course-app-blue"* ]];
+          then
+            INACTIVE_SERVICE="dev-devops-course-app-blue"
+          elif [[ ${INACTIVE_TARGET_GROUP} == *"dev-devops-course-app-green"* ]];
+          then
+            INACTIVE_TARGET_GROUP="dev-devops-course-app-green"
+          else
+            echo "Failed to find inactive service."
+            exit 1
+          fi
+
           echo $INACTIVE_TARGET_GROUP
           echo "test=${INACTIVE_TARGET_GROUP}" >> $GITHUB_OUTPUT
       - name: Test
